#pragma once
#include <DPDA/token.h>

CREATE_TOKEN_CONSTEXPR(__SYMS_BEGIN, "SYMBOLS_BEGIN");

CREATE_TOKEN_CONSTEXPR(ASSIGN, "ASSIGN");
CREATE_TOKEN_CONSTEXPR(CASE, "CASE");
CREATE_TOKEN_CONSTEXPR(CLASS, "CLASS");
CREATE_TOKEN_CONSTEXPR(DARROW, "DARROW");
CREATE_TOKEN_CONSTEXPR(ELSE, "ELSE");
CREATE_TOKEN_CONSTEXPR(ESAC, "ESAC");
CREATE_TOKEN_CONSTEXPR(FI, "FI");
CREATE_TOKEN_CONSTEXPR(IF, "IF");
CREATE_TOKEN_CONSTEXPR(IN, "IN");
CREATE_TOKEN_CONSTEXPR(INHERITS, "INHERITS");
CREATE_TOKEN_CONSTEXPR(ISVOID, "ISVOID");
CREATE_TOKEN_CONSTEXPR(LE, "LE");
CREATE_TOKEN_CONSTEXPR(LET, "LET");
CREATE_TOKEN_CONSTEXPR(LOOP, "LOOP");
CREATE_TOKEN_CONSTEXPR(NEW, "NEW");
CREATE_TOKEN_CONSTEXPR(NOT, "NOT");
CREATE_TOKEN_CONSTEXPR(OF, "OF");
CREATE_TOKEN_CONSTEXPR(POOL, "POOL");
CREATE_TOKEN_CONSTEXPR(THEN, "THEN");
CREATE_TOKEN_CONSTEXPR(WHILE, "WHILE");
CREATE_TOKEN_CONSTEXPR(WS, "WHITESPACE");
CREATE_TOKEN_CONSTEXPR(COMMENT_MULTI, "COMMENT_MULTI");
CREATE_TOKEN_CONSTEXPR(COMMENT_UNCLOSED, "COMMENT_UNCLOSED");


CREATE_TOKEN_CONSTEXPR(INT_CONST, "INT_CONST");
CREATE_TOKEN_CONSTEXPR(OBJECTID, "OBJECTID");
CREATE_TOKEN_CONSTEXPR(TYPEID, "TYPEID");
CREATE_TOKEN_CONSTEXPR(BOOL_CONST_TRUE, "BOOL_CONST");
CREATE_TOKEN_CONSTEXPR(BOOL_CONST_FALSE, "BOOL_CONST");
CREATE_TOKEN_CONSTEXPR(STR_CONST, "STR_CONST");
CREATE_TOKEN_CONSTEXPR(ERROR, "ERROR");

